export const SET_USER_INFOS = 'SET_USER_INFOS';
export const DISABLE_BUTTON = 'DISABLE_BUTTON';

export const SAVE_RECORD_STOCK = 'SAVE_RECORD_STOCK';
export const SAVE_ACCOUNT_BALANCE = 'SAVE_ACCOUNT_BALANCE';